headers:
  - Instance Type
  - TermType
  - Tenancy
  - Operating System
  - License Model
  - CapacityStatus
  - Pre Installed S/W
  - Unit
  - PricePerUnit
  - Currency
selection_criteria:
  CapacityStatus:
    - Used
  Instance Type:
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large
    - t3.xlarge
    - t3.2xlarge
    - t3a.large
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - r4.xlarge
    - r5.large
    - r5.xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - r5.24xlarge
    - r5.12xlarge
    - c5.xlarge
  License Model:
    - No License required
  Operating System:
    - Linux
    - Windows
  Pre Installed S/W:
    - NA
  Tenancy:
    - Shared
  TermType:
    - OnDemand